"""partner-agent — Sprint 8 Phase 8B Slice 5 (demo cross-org partner).

Stands in for a *different* organisation's A2A endpoint. Exposes a single
JSON-RPC 2.0 endpoint on HTTPS :8443 with a self-signed certificate whose
SAN is `partner-agent.example.com`. The cert is generated at container
build time — see docker/partner_agent/Dockerfile.

Behaviour mirrors docker/agent.py's /a2a handler: `tasks/send` echoes the
incoming text back wrapped in an A2A envelope; any other method returns
a JSON-RPC method-not-found error. There is no policy / auth here —
enforcement is the *caller's* control plane's job, not the partner's.
"""

from __future__ import annotations

import os

import uvicorn
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

app = FastAPI()
AGENT_ID = os.environ.get("PARTNER_AGENT_ID", "partner-agent")


@app.get("/healthz")
async def healthz() -> dict[str, str]:
    return {"status": "ok", "agent_id": AGENT_ID}


@app.post("/")
@app.post("/a2a")
async def a2a(req: Request) -> JSONResponse:
    body = await req.json()
    rpc_id = body.get("id", "0")
    method = body.get("method", "")
    if method != "tasks/send":
        return JSONResponse(
            {
                "jsonrpc": "2.0",
                "id": rpc_id,
                "error": {"code": -32601, "message": "method not supported"},
            }
        )

    params = body.get("params") or {}
    message = params.get("message") or {}
    parts = message.get("parts") or []
    text = parts[0].get("text", "") if parts else ""
    reply = f"[{AGENT_ID}] cross-org echo: {text}"
    return JSONResponse(
        {
            "jsonrpc": "2.0",
            "id": rpc_id,
            "result": {
                "id": params.get("id", rpc_id),
                "status": {"state": "completed"},
                "artifacts": [{"parts": [{"type": "text", "text": reply}]}],
            },
        }
    )


if __name__ == "__main__":
    # The self-signed cert is generated by the Dockerfile at build time so
    # we don't regen on every boot. Paths are fixed to keep the container
    # contract simple.
    uvicorn.run(
        app,
        host="0.0.0.0",
        # Container runs as root — bind the privileged 443 port so a2a_proxy
        # can use the natural `https://partner-agent.example.com/` URL
        # without embedding a port everywhere (Envoy virtual-host domains,
        # allow-lists, test URLs).
        port=443,
        ssl_certfile="/certs/partner.crt",
        ssl_keyfile="/certs/partner.key",
        log_level="warning",
    )
