# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: envoy/config/core/v3/base.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'envoy/config/core/v3/base.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x65nvoy/config/core/v3/base.proto\x12\x14\x65nvoy.config.core.v3\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\"<\n\x0bHeaderValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x11\n\traw_value\x18\x03 \x01(\x0c\"\xce\x02\n\x11HeaderValueOption\x12\x31\n\x06header\x18\x01 \x01(\x0b\x32!.envoy.config.core.v3.HeaderValue\x12\x34\n\x10keep_empty_value\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12Q\n\rappend_action\x18\x02 \x01(\x0e\x32:.envoy.config.core.v3.HeaderValueOption.HeaderAppendAction\"}\n\x12HeaderAppendAction\x12\x1b\n\x17\x41PPEND_IF_EXISTS_OR_ADD\x10\x00\x12\x11\n\rADD_IF_ABSENT\x10\x01\x12\x1e\n\x1aOVERWRITE_IF_EXISTS_OR_ADD\x10\x02\x12\x17\n\x13OVERWRITE_IF_EXISTS\x10\x03\"?\n\tHeaderMap\x12\x32\n\x07headers\x18\x01 \x03(\x0b\x32!.envoy.config.core.v3.HeaderValue\"\xa7\x01\n\x08Metadata\x12K\n\x0f\x66ilter_metadata\x18\x01 \x03(\x0b\x32\x32.envoy.config.core.v3.Metadata.FilterMetadataEntry\x1aN\n\x13\x46ilterMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct:\x02\x38\x01\x42\x44ZBgithub.com/envoyproxy/go-control-plane/envoy/config/core/v3;corev3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envoy.config.core.v3.base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/envoyproxy/go-control-plane/envoy/config/core/v3;corev3'
  _globals['_METADATA_FILTERMETADATAENTRY']._loaded_options = None
  _globals['_METADATA_FILTERMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_HEADERVALUE']._serialized_start=119
  _globals['_HEADERVALUE']._serialized_end=179
  _globals['_HEADERVALUEOPTION']._serialized_start=182
  _globals['_HEADERVALUEOPTION']._serialized_end=516
  _globals['_HEADERVALUEOPTION_HEADERAPPENDACTION']._serialized_start=391
  _globals['_HEADERVALUEOPTION_HEADERAPPENDACTION']._serialized_end=516
  _globals['_HEADERMAP']._serialized_start=518
  _globals['_HEADERMAP']._serialized_end=581
  _globals['_METADATA']._serialized_start=584
  _globals['_METADATA']._serialized_end=751
  _globals['_METADATA_FILTERMETADATAENTRY']._serialized_start=673
  _globals['_METADATA_FILTERMETADATAENTRY']._serialized_end=751
# @@protoc_insertion_point(module_scope)
