# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto\x12)envoy.extensions.filters.http.ext_proc.v3\"\xf3\x06\n\x0eProcessingMode\x12\x65\n\x13request_header_mode\x18\x01 \x01(\x0e\x32H.envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.HeaderSendMode\x12\x66\n\x14response_header_mode\x18\x02 \x01(\x0e\x32H.envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.HeaderSendMode\x12\x61\n\x11request_body_mode\x18\x03 \x01(\x0e\x32\x46.envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.BodySendMode\x12\x62\n\x12response_body_mode\x18\x04 \x01(\x0e\x32\x46.envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.BodySendMode\x12g\n\x14request_trailer_mode\x18\x05 \x01(\x0e\x32I.envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.TrailerSendMode\x12h\n\x15response_trailer_mode\x18\x06 \x01(\x0e\x32I.envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.TrailerSendMode\"F\n\x0eHeaderSendMode\x12\x12\n\x0eHEADER_DEFAULT\x10\x00\x12\x0f\n\x0bHEADER_SEND\x10\x01\x12\x0f\n\x0bHEADER_SKIP\x10\x02\"d\n\x0c\x42odySendMode\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08STREAMED\x10\x01\x12\x0c\n\x08\x42UFFERED\x10\x02\x12\x14\n\x10\x42UFFERED_PARTIAL\x10\x03\x12\x18\n\x14\x46ULL_DUPLEX_STREAMED\x10\x04\"J\n\x0fTrailerSendMode\x12\x13\n\x0fTRAILER_DEFAULT\x10\x00\x12\x10\n\x0cTRAILER_SEND\x10\x01\x12\x10\n\x0cTRAILER_SKIP\x10\x02\x42]Z[github.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/ext_proc/v3;ext_procv3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envoy.extensions.filters.http.ext_proc.v3.processing_mode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z[github.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/ext_proc/v3;ext_procv3'
  _globals['_PROCESSINGMODE']._serialized_start=111
  _globals['_PROCESSINGMODE']._serialized_end=994
  _globals['_PROCESSINGMODE_HEADERSENDMODE']._serialized_start=746
  _globals['_PROCESSINGMODE_HEADERSENDMODE']._serialized_end=816
  _globals['_PROCESSINGMODE_BODYSENDMODE']._serialized_start=818
  _globals['_PROCESSINGMODE_BODYSENDMODE']._serialized_end=918
  _globals['_PROCESSINGMODE_TRAILERSENDMODE']._serialized_start=920
  _globals['_PROCESSINGMODE_TRAILERSENDMODE']._serialized_end=994
# @@protoc_insertion_point(module_scope)
