"""
Agent-container spawn helper with the full aMaze isolation profile.

NOT used by the step-1 passive orchestrator — agents self-register. Kept
as a reference implementation: when a future sprint adds orchestrator-
driven spawning, this is the template.

The resulting container:

  - Is attached ONLY to amaze-agent-net (internal=true → no internet route).
  - Has HTTP_PROXY / HTTPS_PROXY pre-set to the in-net proxy URL.
  - Runs with dropped Linux capabilities, read-only rootfs, /tmp as tmpfs.
  - Is memory / pid / cpu capped.
  - Trusts the proxy's MITM CA — mounted from the shared named volume
    `amaze-proxy-ca` (read-only).

Design note on the CA mount: the previous version took a host filesystem
path. That's wrong in the single-container model — the CA is generated by
mitmproxy at runtime into a named Docker volume. You can't bind-mount a
path that doesn't exist on the host. Correct shape: mount the NAMED VOLUME
by its name. Docker handles the rest.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass

import docker
import docker.errors
from docker.models.containers import Container

logger = logging.getLogger(__name__)

PROXY_URL = os.environ.get("AMAZE_PROXY_URL", "http://amaze:8080")
AGENT_NETWORK = os.environ.get("AMAZE_AGENT_NETWORK", "amaze_amaze-agent-net")

# Named volume shared with the platform container (written by mitmproxy on
# first boot). Mounted read-only into every spawned sibling at
# /etc/amaze/ca. Matches the convention in docker/Dockerfile.agent-base.
CA_VOLUME_NAME = os.environ.get("AMAZE_PROXY_CA_VOLUME", "amaze-proxy-ca")
CA_MOUNT_PATH = "/etc/amaze/ca"


@dataclass(frozen=True)
class SpawnResult:
    container_id: str
    container_name: str


def spawn_agent_container(
    *,
    session_id: str,
    agent_id: str,
    bearer_token: str,
    image: str,
    env_vars: dict[str, str] | None = None,
    mem_limit: str = "512m",
    cpu_quota: int = 50000,
) -> SpawnResult:
    """Spawn one agent container with the full isolation profile."""

    env: dict[str, str] = {
        "HTTP_PROXY": PROXY_URL,
        "HTTPS_PROXY": PROXY_URL,
        "NO_PROXY": "",
        "AMAZE_SESSION_ID": session_id,
        "AMAZE_AGENT_ID": agent_id,
        "AMAZE_PROXY_URL": PROXY_URL,
        "AMAZE_SESSION_TOKEN": bearer_token,
        "SSL_CERT_FILE": f"{CA_MOUNT_PATH}/mitmproxy-ca-cert.pem",
        "REQUESTS_CA_BUNDLE": f"{CA_MOUNT_PATH}/mitmproxy-ca-cert.pem",
        **(env_vars or {}),
    }

    # Named-volume mount — the docker-py SDK accepts the volume NAME as the
    # outer key (not a host filesystem path) when you want a named volume.
    volumes = {
        CA_VOLUME_NAME: {"bind": CA_MOUNT_PATH, "mode": "ro"},
    }

    container_name = f"amaze-agent-{agent_id}-{session_id[:8]}"

    client = docker.from_env()
    container: Container = client.containers.run(
        image=image,
        name=container_name,
        detach=True,
        network=AGENT_NETWORK,
        environment=env,
        volumes=volumes,
        security_opt=["no-new-privileges:true"],
        cap_drop=["ALL"],
        read_only=True,
        tmpfs={"/tmp": "size=256m,noexec,nosuid"},
        mem_limit=mem_limit,
        pids_limit=512,
        cpu_quota=cpu_quota,
        cpu_period=100000,
        userns_mode="",
    )

    logger.info(
        "spawned agent container name=%s image=%s session=%s agent=%s",
        container_name,
        image,
        session_id,
        agent_id,
    )
    return SpawnResult(container_id=container.id, container_name=container_name)


def stop_agent_container(container_id: str) -> None:
    """Idempotent stop + remove."""
    client = docker.from_env()
    try:
        container = client.containers.get(container_id)
        container.stop(timeout=10)
        container.remove(force=True)
    except docker.errors.NotFound:
        return
